AWSTemplateFormatVersion: "2010-09-09"
Description: mujinyoyaku DynamoDB
Parameters:
  Prefix: 
    Description: Resource Prefix 
    Type: String 
  HashKey:
    Type: String
  RangeKey:
    Type: String
  Gsi1Pk:
    Type: String
  Gsi2Pk:
    Type: String
  Gsi2Sk:
    Type: String
  Lsi1Sk:
    Type: String
  Lsi2Sk:
    Type: String
  Lsi3Sk:
    Type: String
  Gsi1IndexName:
    Type: String
  Gsi2IndexName:
    Type: String
  Lsi1IndexName:
    Type: String
  Lsi2IndexName:
    Type: String
  Lsi3IndexName:
    Type: String

Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Prefix}-main
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref HashKey
          AttributeType: S
        - AttributeName: !Ref RangeKey
          AttributeType: S
        - AttributeName: !Ref Gsi2Pk
          AttributeType: S
        - AttributeName: !Ref Gsi2Sk
          AttributeType: S
        - AttributeName: !Ref Lsi1Sk
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref HashKey
          KeyType: HASH
        - AttributeName: !Ref RangeKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref Gsi1IndexName
          KeySchema:
            - AttributeName: !Ref Gsi1Pk
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref Gsi2IndexName
          KeySchema:
            - AttributeName: !Ref RangeKey
              KeyType: HASH
            - AttributeName: !Ref Lsi2Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: !Ref Lsi1IndexName
          KeySchema:
            - AttributeName: !Ref HashKey
              KeyType: HASH
            - AttributeName: !Ref Lsi1Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref Lsi2IndexName
          KeySchema:
            - AttributeName: !Ref HashKey
              KeyType: HASH
            - AttributeName: !Ref Lsi2Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref Lsi3IndexName
          KeySchema:
            - AttributeName: !Ref HashKey
              KeyType: HASH
            - AttributeName: !Ref Lsi3Sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  MainTableArn:
    Description: MainTableArn
    Value: !GetAtt MainTable.Arn
    Export:
      Name: !Sub ${Prefix}-MainTableArn
  MainTableName:
    Description: MainTableName
    Value: !Ref MainTable
    Export:
      Name: !Sub ${Prefix}-MainTableName